behaviors:
  Tetris:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 16384
      learning_rate: 1.2e-3
      beta: 3.0e-3
      epsilon: 0.26
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    max_steps: 2.0e+8
    time_horizon: 2048
    summary_freq: 100000
    keep_checkpoints: 30
    checkpoint_interval: 5000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.75
      save_steps: 20000
      swap_steps: 20000
      team_change: 100000

