behaviors:
  Tetris:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 16384
      learning_rate: 9.0e-4
      beta: 2.0e-2
      epsilon: 0.24
      lambd: 0.97
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.3
        gamma: 0.99
        demo_path: Assets/Demonstrations/TetrisCopium2.demo
    max_steps: 8.0e+7
    time_horizon: 2048
    summary_freq: 15000
    keep_checkpoints: 20
    checkpoint_interval: 250000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 10000
      team_change: 100000

