behaviors:
  Tetris:
    trainer_type: sac
    hyperparameters:
      batch_size: 2048
      buffer_size: 131072
      buffer_init_steps: 5000
      init_entcoef: 0.7
      learning_rate: 1.2e-3
      steps_per_update: 64
      learning_rate_schedule: constant
      save_replay_buffer: true
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    max_steps: 2.0e+8
    time_horizon: 2048
    summary_freq: 100000
    keep_checkpoints: 30
    checkpoint_interval: 5000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.75
      save_steps: 20000
      swap_steps: 20000
      team_change: 100000

