behaviors:
  Tetris:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 16384
      learning_rate: 3.0e-4
      beta: 4.5e-3
      epsilon: 0.21
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 640
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.98
        strength: 1.0
    max_steps: 2.5e+8
    time_horizon: 2048
    summary_freq: 100000
    keep_checkpoints: 30
    checkpoint_interval: 5000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 20000
      swap_steps: 20000
      team_change: 100000

environment_parameters:
  game_over_height: 19.0
  piece_height_reward: 0.0
  row_near_filled_reward: 0.0
  1_line_clear_reward: 0.0
  2_line_clear_reward: 1.0
  3_line_clear_reward: 1.0
  4_line_clear_reward: 2.0
  hole_made_penalty: -0.0
  valid_piece_pos_reward: 0.0
