behaviors:
  Tetris:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 8192
      learning_rate: 3.0e-4
      beta: 
        opt_values: [4.0e-3, 3.0e-3, 2.5e-3]
      epsilon:
        opt_values: [0.3, 0.2, 0.15]
      lambd: 
        opt_values: [0.98, 0.95, 0.92]
      num_epoch: 
        opt_values: [2, 3, 4]
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 
        opt_values: [256, 512, 1024]
      num_layers: 
        opt_values: [2, 3, 4]
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.18
        gamma: 0.99
        demo_path: Assets/Demonstrations/Testrisaaaa.demo
    max_steps: 5.0e+6
    time_horizon: 
      opt_values: [64, 128, 256]
    summary_freq: 5000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.5
      save_steps: 2000
      swap_steps: 2000
      team_change: 8000

