behaviors:
  Tetris:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 24576
      learning_rate: 0.6e-3
      beta: 4.0e-3
      epsilon: 0.135
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      gail:
        strength: 0.3
        gamma: 0.99
        demo_path: Assets/Demonstrations/TetrisAgainNoStackedVector.demo
    max_steps: 3.2e+8
    time_horizon: 2048
    summary_freq: 100000
    keep_checkpoints: 30
    checkpoint_interval: 1000000
    self_play:
      window: 10
      play_against_latest_model_ratio: 0.75
      save_steps: 20000
      swap_steps: 20000
      team_change: 100000

